volcano-location: none

activation-distance: 100

blocks-per-wave: 30

mobs-per-wave: 15

antilag-mechanism: true

each-wave-time: 10

warning-message: true
warning-title: "&c&lBe Careful!"
warning-subtitle: "&6There is a Volcano near to you!"

specified-mobs:
  - BLAZE:100

specified-blocks:
  - STONE:100
  - DIAMOND_BLOCK:20
  - GOLD_BLOCK:70